project_name: price-feeder

env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod download

builds:
  - main: ./
    id: "price-feeder"
    binary: price-feeder
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/umee-network/umee/price-feeder/cmd.Version={{ replace .Version "price-feeder/" "price-feeder-" }} -X github.com/umee-network/umee/price-feeder/cmd.Commit={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ replace .Version "price-feeder/" "price-feeder-" }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - LICENSE

release:
  disable: false

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: 'SHA256SUMS-{{ replace .Version "price-feeder/" "price-feeder-" }}.txt'
  algorithm: sha256

changelog:
  skip: false
