---
project_name: umee

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: umee-network
    name: umee
  name_template: "{{.Version}} Release Notes"

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: true
