queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:Automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Backport patches to the release/v4.0.x branch
    conditions:
      - base=main
      - label=S:backport/v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x

  - name: Backport patches to the release/v4.1.x branch
    conditions:
      - base=main
      - label=S:backport/v4.1.x
    actions:
      backport:
        branches:
          - release/v4.1.x
