pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:Automerge
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
  - name: Backport patches to release/v0.1.x branch
    conditions:
      - base=main
      - label=S:backport/v0.1.x
    actions:
      backport:
        branches:
          - release/v0.1.x
