queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:Automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Backport patches to the release/v0.8.x branch
    conditions:
      - base=main
      - label=S:backport/v0.8.x
    actions:
      backport:
        branches:
          - release/v0.8.x

  - name: Backport patches to the release/v1.x.x branch
    conditions:
      - base=main
      - label=S:backport/v1.x.x
    actions:
      backport:
        branches:
          - release/v1.x.x

  - name: Backport patches to the release/v2.x.x branch
    conditions:
      - base=main
      - label=S:backport/v2.x.x
    actions:
      backport:
        branches:
          - release/v2.x.x

  - name: Backport patches to the release/v2.x.x branch
    conditions:
      - base=main
      - label=S:backport/v2.x.x
    actions:
      backport:
        branches:
          - release/v2.x.x

  - name: Backport patches to the release/price-feeder/v0.1.x branch
    conditions:
      - base=main
      - label=S:backport/price-feeder/v0.1.x
    actions:
      backport:
        branches:
          - release/price-feeder/v0.1.x

  - name: Backport patches to the release/price-feeder/v0.2.x branch
    conditions:
      - base=main
      - label=S:backport/price-feeder/v0.2.x
    actions:
      backport:
        branches:
          - release/price-feeder/v0.2.x
