# Sets the default severity to "error"
severity = "error"

# Sets the default failure confidence. This means that linting errors
# with less than 0 confidence will be ignored.
confidence = 0

# https://github.com/mgechev/revive#configuration

# Recommended configuration, minus [rule.exported] and [rule.package-comments]
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]

# https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
