# Sets the default severity to "error"
severity = "error"

# Sets the default failure confidence. This means that linting errors
# with less than 0 confidence will be ignored.
confidence = 0

# https://github.com/mgechev/revive#configuration

# Recommended configuration, minus [rule.exported] and [rule.package-comments]
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.errorf]
#[rule.exported]
#[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
#[rule.package-comments]
[rule.range]
#[rule.receiver-naming]
#[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
#[rule.unused-parameter]
[rule.var-declaration]
#[rule.var-naming]

# Additional rules
[rule.time-equal]
[rule.get-return]
#[rule.deep-exit]
[rule.unnecessary-stmt]
