name: PackAndDistribute
inputs:
  GCP_SA_KEY:
    description: service account key (base64 encoded json)
    required: true
runs:
  using: composite
  steps:
    - name: Pack & Distribute Umee Images
      shell: bash
      run: |
        pushd /tmp
        echo -n ${{ inputs.GCP_SA_KEY }} | base64 --decode > gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-service-key.json"
        curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
        tar -xzf google-cloud-sdk-367.0.0-linux-x86_64.tar.gz
        ./google-cloud-sdk/install.sh --usage-reporting false
        gcloud auth activate-service-account --key-file gcloud-service-key.json
        gcloud auth configure-docker us-docker.pkg.dev
        popd

        pushd infra/packer
        bin/pack-and-distribute
        popd
