package types

const (
	EventTypeObservation    = "observation"
	EventTypeOutgoingBatch  = "outgoing_batch"
	EventTypeAttestation    = "attestation"
	EventTypeValsetSlashing = "valset_slashing"
	EventTypeBatchSlashing  = "batch_slashing"

	EventTypeMultisigUpdateRequest    = "multisig_update_request"
	EventTypeOutgoingBatchCanceled    = "outgoing_batch_canceled"
	EventTypeBridgeWithdrawalReceived = "withdrawal_received"
	EventTypeBridgeDepositReceived    = "deposit_received"
	EventTypeBridgeWithdrawCanceled   = "withdraw_canceled"

	AttributeKeyAttestationID           = "attestation_id"
	AttributeKeyBatchConfirmKey         = "batch_confirm_key"
	AttributeKeyValsetConfirmKey        = "valset_confirm_key"
	AttributeKeyMultisigID              = "multisig_id"
	AttributeKeyOutgoingBatchID         = "batch_id"
	AttributeKeyOutgoingTXID            = "outgoing_tx_id"
	AttributeKeyAttestationType         = "attestation_type"
	AttributeKeyContract                = "bridge_contract"
	AttributeKeyNonce                   = "nonce"
	AttributeKeyValsetNonce             = "valset_nonce"
	AttributeKeyBatchNonce              = "batch_nonce"
	AttributeKeyBridgeChainID           = "bridge_chain_id"
	AttributeKeySetOperatorAddr         = "set_operator_address"
	AttributeKeyBadEthSignature         = "bad_eth_signature"
	AttributeKeyBadEthSignatureSubject  = "bad_eth_signature_subject"
	AttributeKeySetOrchestratorAddr     = "set_orchestrator_address"
	AttributeKeySetEthereumAddr         = "set_ethereum_address"
	AttributeKeyValidatorAddr           = "validator_address"
	AttributeKeySendToCosmosAmount      = "send_to_cosmos_amount"
	AttributeKeySendToCosmosEventNonce  = "send_to_cosmos_event_nonce"
	AttributeKeySendToCosmosToken       = "send_to_cosmos_token"
	AttributeKeyERC20DeployedToken      = "erc20_deployed_token"
	AttributeKeyERC20DeployedEventNonce = "erc20_deployed_event_nonce"
	AttributeKeyValsetUpdatedEventNonce = "valset_updated_event_nonce"
	AttributeKeyConsensusAddress        = "consensus_address"
)
