// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: umee/ugov/v1/query.proto

package ugov

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryMinGasPrice is a request type.
type QueryMinGasPrice struct {
}

func (m *QueryMinGasPrice) Reset()         { *m = QueryMinGasPrice{} }
func (m *QueryMinGasPrice) String() string { return proto.CompactTextString(m) }
func (*QueryMinGasPrice) ProtoMessage()    {}
func (*QueryMinGasPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{0}
}
func (m *QueryMinGasPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMinGasPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMinGasPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMinGasPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMinGasPrice.Merge(m, src)
}
func (m *QueryMinGasPrice) XXX_Size() int {
	return m.Size()
}
func (m *QueryMinGasPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMinGasPrice.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMinGasPrice proto.InternalMessageInfo

// QueryMinGasPriceResponse response type.
type QueryMinGasPriceResponse struct {
	MinGasPrice types.DecCoin `protobuf:"bytes,1,opt,name=min_gas_price,json=minGasPrice,proto3" json:"min_gas_price"`
}

func (m *QueryMinGasPriceResponse) Reset()         { *m = QueryMinGasPriceResponse{} }
func (m *QueryMinGasPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMinGasPriceResponse) ProtoMessage()    {}
func (*QueryMinGasPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{1}
}
func (m *QueryMinGasPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMinGasPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMinGasPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMinGasPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMinGasPriceResponse.Merge(m, src)
}
func (m *QueryMinGasPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMinGasPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMinGasPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMinGasPriceResponse proto.InternalMessageInfo

// QueryEmergencyGroup request type.
type QueryEmergencyGroup struct {
}

func (m *QueryEmergencyGroup) Reset()         { *m = QueryEmergencyGroup{} }
func (m *QueryEmergencyGroup) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyGroup) ProtoMessage()    {}
func (*QueryEmergencyGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{2}
}
func (m *QueryEmergencyGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyGroup.Merge(m, src)
}
func (m *QueryEmergencyGroup) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyGroup.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyGroup proto.InternalMessageInfo

// QueryEmergencyGroupResponse response type.
type QueryEmergencyGroupResponse struct {
	EmergencyGroup string `protobuf:"bytes,1,opt,name=emergency_group,json=emergencyGroup,proto3" json:"emergency_group,omitempty"`
}

func (m *QueryEmergencyGroupResponse) Reset()         { *m = QueryEmergencyGroupResponse{} }
func (m *QueryEmergencyGroupResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyGroupResponse) ProtoMessage()    {}
func (*QueryEmergencyGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{3}
}
func (m *QueryEmergencyGroupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyGroupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyGroupResponse.Merge(m, src)
}
func (m *QueryEmergencyGroupResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyGroupResponse proto.InternalMessageInfo

// QueryInflationParams request type.
type QueryInflationParams struct {
}

func (m *QueryInflationParams) Reset()         { *m = QueryInflationParams{} }
func (m *QueryInflationParams) String() string { return proto.CompactTextString(m) }
func (*QueryInflationParams) ProtoMessage()    {}
func (*QueryInflationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{4}
}
func (m *QueryInflationParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationParams.Merge(m, src)
}
func (m *QueryInflationParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationParams proto.InternalMessageInfo

// QueryInflationParamsResponse response type.
type QueryInflationParamsResponse struct {
	InflationParams InflationParams `protobuf:"bytes,1,opt,name=inflation_params,json=inflationParams,proto3" json:"inflation_params"`
}

func (m *QueryInflationParamsResponse) Reset()         { *m = QueryInflationParamsResponse{} }
func (m *QueryInflationParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInflationParamsResponse) ProtoMessage()    {}
func (*QueryInflationParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{5}
}
func (m *QueryInflationParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationParamsResponse.Merge(m, src)
}
func (m *QueryInflationParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationParamsResponse proto.InternalMessageInfo

// QueryInflationCycleStartTime request type.
type QueryInflationCycleStartTime struct {
}

func (m *QueryInflationCycleStartTime) Reset()         { *m = QueryInflationCycleStartTime{} }
func (m *QueryInflationCycleStartTime) String() string { return proto.CompactTextString(m) }
func (*QueryInflationCycleStartTime) ProtoMessage()    {}
func (*QueryInflationCycleStartTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{6}
}
func (m *QueryInflationCycleStartTime) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationCycleStartTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationCycleStartTime.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationCycleStartTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationCycleStartTime.Merge(m, src)
}
func (m *QueryInflationCycleStartTime) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationCycleStartTime) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationCycleStartTime.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationCycleStartTime proto.InternalMessageInfo

// QueryInflationCycleStartTimeResponse response type.
type QueryInflationCycleStartTimeResponse struct {
	InflationCycleStart *time.Time `protobuf:"bytes,1,opt,name=inflation_cycle_start,json=inflationCycleStart,proto3,stdtime" json:"inflation_cycle_start,omitempty"`
}

func (m *QueryInflationCycleStartTimeResponse) Reset()         { *m = QueryInflationCycleStartTimeResponse{} }
func (m *QueryInflationCycleStartTimeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInflationCycleStartTimeResponse) ProtoMessage()    {}
func (*QueryInflationCycleStartTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25fa04679024a47d, []int{7}
}
func (m *QueryInflationCycleStartTimeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationCycleStartTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationCycleStartTimeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationCycleStartTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationCycleStartTimeResponse.Merge(m, src)
}
func (m *QueryInflationCycleStartTimeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationCycleStartTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationCycleStartTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationCycleStartTimeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryMinGasPrice)(nil), "umee.ugov.v1.QueryMinGasPrice")
	proto.RegisterType((*QueryMinGasPriceResponse)(nil), "umee.ugov.v1.QueryMinGasPriceResponse")
	proto.RegisterType((*QueryEmergencyGroup)(nil), "umee.ugov.v1.QueryEmergencyGroup")
	proto.RegisterType((*QueryEmergencyGroupResponse)(nil), "umee.ugov.v1.QueryEmergencyGroupResponse")
	proto.RegisterType((*QueryInflationParams)(nil), "umee.ugov.v1.QueryInflationParams")
	proto.RegisterType((*QueryInflationParamsResponse)(nil), "umee.ugov.v1.QueryInflationParamsResponse")
	proto.RegisterType((*QueryInflationCycleStartTime)(nil), "umee.ugov.v1.QueryInflationCycleStartTime")
	proto.RegisterType((*QueryInflationCycleStartTimeResponse)(nil), "umee.ugov.v1.QueryInflationCycleStartTimeResponse")
}

func init() { proto.RegisterFile("umee/ugov/v1/query.proto", fileDescriptor_25fa04679024a47d) }

var fileDescriptor_25fa04679024a47d = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x34, 0x10, 0x78, 0xb0, 0x4d, 0xde, 0xc6, 0x4a, 0xb6, 0xa5, 0x23, 0xc0, 0x04,
	0x48, 0xb1, 0xd5, 0x21, 0x3e, 0xc0, 0xba, 0xc1, 0xc4, 0x01, 0x34, 0xba, 0x1d, 0x10, 0x97, 0xe2,
	0x64, 0x5e, 0xb0, 0x68, 0xec, 0x10, 0x27, 0x85, 0x72, 0x42, 0x48, 0x1c, 0xb8, 0x4d, 0xe2, 0x0b,
	0xf0, 0x21, 0x38, 0xf1, 0x09, 0x7a, 0x9c, 0xe0, 0xc2, 0x69, 0x40, 0xcb, 0x07, 0x41, 0x71, 0xfe,
	0xac, 0x09, 0xa5, 0xe5, 0x56, 0xfb, 0x79, 0xfa, 0x3e, 0xbf, 0x37, 0x7e, 0x40, 0x35, 0xf2, 0x28,
	0xc5, 0x91, 0x2b, 0x3a, 0xb8, 0x53, 0xc7, 0x2f, 0x23, 0x1a, 0x74, 0x91, 0x1f, 0x88, 0x50, 0xc0,
	0x8b, 0xb1, 0x82, 0x62, 0x05, 0x75, 0xea, 0xba, 0xe1, 0x08, 0xe9, 0x09, 0x89, 0x6d, 0x22, 0x29,
	0xee, 0xd4, 0x6d, 0x1a, 0x92, 0x3a, 0x76, 0x04, 0xe3, 0x89, 0x5b, 0xbf, 0x92, 0xe8, 0x2d, 0x75,
	0xc2, 0xc9, 0x21, 0x95, 0x16, 0x5c, 0xe1, 0x8a, 0xe4, 0x3e, 0xfe, 0x95, 0xde, 0xae, 0xb8, 0x42,
	0xb8, 0x6d, 0x8a, 0x89, 0xcf, 0x30, 0xe1, 0x5c, 0x84, 0x24, 0x64, 0x82, 0x67, 0xff, 0xa9, 0xa5,
	0xaa, 0x3a, 0xd9, 0xd1, 0x21, 0x0e, 0x99, 0x47, 0x65, 0x48, 0x3c, 0x3f, 0x35, 0x2c, 0x15, 0xb8,
	0x15, 0xa5, 0x12, 0x4c, 0x08, 0xe6, 0x1e, 0xc7, 0x5b, 0x3c, 0x64, 0x7c, 0x87, 0xc8, 0xdd, 0x80,
	0x39, 0xd4, 0xb4, 0x41, 0xb5, 0x7c, 0xd7, 0xa4, 0xd2, 0x17, 0x5c, 0x52, 0x78, 0x1f, 0x5c, 0xf2,
	0x18, 0x6f, 0xb9, 0x24, 0x66, 0x67, 0x0e, 0xad, 0x6a, 0x6b, 0xda, 0xcd, 0xe9, 0x8d, 0x15, 0x94,
	0xee, 0x10, 0x2f, 0x8c, 0xd2, 0x85, 0xd1, 0x36, 0x75, 0xb6, 0x04, 0xe3, 0x8d, 0xa9, 0xde, 0x49,
	0xad, 0xd2, 0x9c, 0xf6, 0x86, 0x32, 0x16, 0xc1, 0xbc, 0xca, 0xb8, 0xe7, 0xd1, 0xc0, 0xa5, 0xdc,
	0xe9, 0xee, 0x04, 0x22, 0xf2, 0xcd, 0x67, 0x60, 0x79, 0xc4, 0x75, 0x9e, 0xbe, 0x09, 0x66, 0x69,
	0xa6, 0xb4, 0xdc, 0x58, 0x52, 0xf9, 0x17, 0x1a, 0xd5, 0xaf, 0x9f, 0xad, 0x85, 0x14, 0x61, 0xf3,
	0xe0, 0x20, 0xa0, 0x52, 0xee, 0x85, 0x01, 0xe3, 0x6e, 0x73, 0x86, 0x16, 0x13, 0x2e, 0x83, 0x05,
	0x95, 0xf0, 0x80, 0x1f, 0xb6, 0xd5, 0x37, 0xdc, 0x25, 0x01, 0xf1, 0xa4, 0xc9, 0xc1, 0xca, 0xa8,
	0xfb, 0x3c, 0xfa, 0x11, 0x98, 0x63, 0x99, 0xd4, 0xf2, 0x95, 0x96, 0xee, 0xbe, 0x8a, 0x86, 0x9f,
	0x1e, 0x95, 0x06, 0xa4, 0xcb, 0xcf, 0xb2, 0x52, 0x9e, 0x51, 0xce, 0xdb, 0xea, 0x3a, 0x6d, 0xba,
	0x17, 0x92, 0x20, 0xdc, 0x67, 0x1e, 0x35, 0xdf, 0x6a, 0xe0, 0xfa, 0x38, 0x43, 0x0e, 0xf6, 0x04,
	0x2c, 0x9e, 0x82, 0x39, 0xb1, 0xa7, 0x25, 0x63, 0x53, 0x4a, 0xa7, 0xa3, 0xa4, 0x1b, 0x28, 0xeb,
	0x06, 0xda, 0xcf, 0xba, 0xd1, 0x38, 0xdf, 0x3b, 0xa9, 0x69, 0x47, 0x3f, 0x6a, 0x5a, 0x73, 0x9e,
	0xfd, 0x9d, 0xb2, 0xf1, 0x65, 0x0a, 0x9c, 0x55, 0x08, 0xf0, 0x0d, 0x98, 0x1e, 0x2a, 0x03, 0x34,
	0x8a, 0x1b, 0x97, 0xcb, 0xa2, 0xaf, 0x8f, 0xd7, 0x33, 0x74, 0xf3, 0xda, 0xbb, 0x6f, 0xbf, 0x3f,
	0x9e, 0x59, 0x85, 0xcb, 0xb8, 0x50, 0x4f, 0x8f, 0x71, 0xcb, 0x25, 0xd2, 0x52, 0x05, 0x83, 0xef,
	0x35, 0x30, 0x53, 0xac, 0x03, 0xbc, 0x3a, 0x62, 0x7e, 0xd1, 0xa2, 0xdf, 0x9a, 0x68, 0xc9, 0x29,
	0x6e, 0x28, 0x8a, 0x1a, 0x5c, 0x2d, 0x52, 0xe4, 0xbd, 0xb1, 0x54, 0xd1, 0xe0, 0x07, 0x0d, 0xcc,
	0x96, 0xde, 0x16, 0x9a, 0x23, 0x52, 0x4a, 0x1e, 0xfd, 0xf6, 0x64, 0x4f, 0x8e, 0xb2, 0xae, 0x50,
	0xd6, 0xa0, 0x51, 0x44, 0xc9, 0x1f, 0xc7, 0x4a, 0x8a, 0x07, 0x3f, 0x69, 0x60, 0xe9, 0x1f, 0xbd,
	0x80, 0x63, 0xf3, 0x8a, 0x5e, 0x7d, 0xe3, 0xff, 0xbd, 0x93, 0x3e, 0xd7, 0x29, 0xa3, 0xea, 0x60,
	0x63, 0xbb, 0xf7, 0xcb, 0xa8, 0xf4, 0xfa, 0x86, 0x76, 0xdc, 0x37, 0xb4, 0x9f, 0x7d, 0x43, 0x3b,
	0x1a, 0x18, 0x95, 0xe3, 0x81, 0x51, 0xf9, 0x3e, 0x30, 0x2a, 0x4f, 0xd7, 0x5d, 0x16, 0x3e, 0x8f,
	0x6c, 0xe4, 0x08, 0x4f, 0x8d, 0xb1, 0x38, 0x0d, 0x5f, 0x89, 0xe0, 0x45, 0x32, 0xb3, 0x73, 0x17,
	0xbf, 0x56, 0x83, 0xed, 0x73, 0xaa, 0xb5, 0x77, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x04, 0xf0,
	0x52, 0x05, 0x78, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// MinGasPrice returns minimum transaction fees.
	MinGasPrice(ctx context.Context, in *QueryMinGasPrice, opts ...grpc.CallOption) (*QueryMinGasPriceResponse, error)
	// EmergencyGroup returns emergency group address
	EmergencyGroup(ctx context.Context, in *QueryEmergencyGroup, opts ...grpc.CallOption) (*QueryEmergencyGroupResponse, error)
	// InflationParams returns params of inflation reduction rates
	InflationParams(ctx context.Context, in *QueryInflationParams, opts ...grpc.CallOption) (*QueryInflationParamsResponse, error)
	// InflationCycleStartTime returns inflation cycle start time
	InflationCycleStartTime(ctx context.Context, in *QueryInflationCycleStartTime, opts ...grpc.CallOption) (*QueryInflationCycleStartTimeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MinGasPrice(ctx context.Context, in *QueryMinGasPrice, opts ...grpc.CallOption) (*QueryMinGasPriceResponse, error) {
	out := new(QueryMinGasPriceResponse)
	err := c.cc.Invoke(ctx, "/umee.ugov.v1.Query/MinGasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EmergencyGroup(ctx context.Context, in *QueryEmergencyGroup, opts ...grpc.CallOption) (*QueryEmergencyGroupResponse, error) {
	out := new(QueryEmergencyGroupResponse)
	err := c.cc.Invoke(ctx, "/umee.ugov.v1.Query/EmergencyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InflationParams(ctx context.Context, in *QueryInflationParams, opts ...grpc.CallOption) (*QueryInflationParamsResponse, error) {
	out := new(QueryInflationParamsResponse)
	err := c.cc.Invoke(ctx, "/umee.ugov.v1.Query/InflationParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InflationCycleStartTime(ctx context.Context, in *QueryInflationCycleStartTime, opts ...grpc.CallOption) (*QueryInflationCycleStartTimeResponse, error) {
	out := new(QueryInflationCycleStartTimeResponse)
	err := c.cc.Invoke(ctx, "/umee.ugov.v1.Query/InflationCycleStartTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// MinGasPrice returns minimum transaction fees.
	MinGasPrice(context.Context, *QueryMinGasPrice) (*QueryMinGasPriceResponse, error)
	// EmergencyGroup returns emergency group address
	EmergencyGroup(context.Context, *QueryEmergencyGroup) (*QueryEmergencyGroupResponse, error)
	// InflationParams returns params of inflation reduction rates
	InflationParams(context.Context, *QueryInflationParams) (*QueryInflationParamsResponse, error)
	// InflationCycleStartTime returns inflation cycle start time
	InflationCycleStartTime(context.Context, *QueryInflationCycleStartTime) (*QueryInflationCycleStartTimeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MinGasPrice(ctx context.Context, req *QueryMinGasPrice) (*QueryMinGasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MinGasPrice not implemented")
}
func (*UnimplementedQueryServer) EmergencyGroup(ctx context.Context, req *QueryEmergencyGroup) (*QueryEmergencyGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyGroup not implemented")
}
func (*UnimplementedQueryServer) InflationParams(ctx context.Context, req *QueryInflationParams) (*QueryInflationParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InflationParams not implemented")
}
func (*UnimplementedQueryServer) InflationCycleStartTime(ctx context.Context, req *QueryInflationCycleStartTime) (*QueryInflationCycleStartTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InflationCycleStartTime not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MinGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMinGasPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MinGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umee.ugov.v1.Query/MinGasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MinGasPrice(ctx, req.(*QueryMinGasPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EmergencyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmergencyGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EmergencyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umee.ugov.v1.Query/EmergencyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EmergencyGroup(ctx, req.(*QueryEmergencyGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InflationParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInflationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InflationParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umee.ugov.v1.Query/InflationParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InflationParams(ctx, req.(*QueryInflationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InflationCycleStartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInflationCycleStartTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InflationCycleStartTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umee.ugov.v1.Query/InflationCycleStartTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InflationCycleStartTime(ctx, req.(*QueryInflationCycleStartTime))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "umee.ugov.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MinGasPrice",
			Handler:    _Query_MinGasPrice_Handler,
		},
		{
			MethodName: "EmergencyGroup",
			Handler:    _Query_EmergencyGroup_Handler,
		},
		{
			MethodName: "InflationParams",
			Handler:    _Query_InflationParams_Handler,
		},
		{
			MethodName: "InflationCycleStartTime",
			Handler:    _Query_InflationCycleStartTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "umee/ugov/v1/query.proto",
}

func (m *QueryMinGasPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMinGasPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMinGasPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryMinGasPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMinGasPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMinGasPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinGasPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyGroupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyGroupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyGroupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EmergencyGroup) > 0 {
		i -= len(m.EmergencyGroup)
		copy(dAtA[i:], m.EmergencyGroup)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EmergencyGroup)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInflationParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInflationParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.InflationParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInflationCycleStartTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationCycleStartTime) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationCycleStartTime) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInflationCycleStartTimeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationCycleStartTimeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationCycleStartTimeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InflationCycleStart != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.InflationCycleStart, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.InflationCycleStart):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintQuery(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMinGasPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryMinGasPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinGasPrice.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEmergencyGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmergencyGroupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EmergencyGroup)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInflationParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInflationParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InflationParams.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryInflationCycleStartTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInflationCycleStartTimeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.InflationCycleStart != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.InflationCycleStart)
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMinGasPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMinGasPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMinGasPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMinGasPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMinGasPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMinGasPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyGroupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyGroupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyGroupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyGroup", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmergencyGroup = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationCycleStartTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationCycleStartTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationCycleStartTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationCycleStartTimeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationCycleStartTimeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationCycleStartTimeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationCycleStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InflationCycleStart == nil {
				m.InflationCycleStart = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.InflationCycleStart, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
