name: GitHub Pages
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # If you're using actions/checkout@v2 you must set persist-credentials to
      # false in most cases for the deployment to work correctly.
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # This example project is built using npm and outputs the result to the
      # 'build' folder. Replace with the commands required to build your project,
      # or remove this step entirely if your site is pre-built.
      - name: Install and Build 🔧
        run: |
          cd vue
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: vue/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
