# This workflow helps with creating docker images.
# This job will only be triggered when a tag (vX.X.x) is pushed
name: Price Feeder Docker Release
on:
  push:
    tags:
      - "price-feeder/v*.*.*"

jobs:
  price-feeder-docker:
    name: price-feeder Docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: umee-network/price-feeder
          tags: 
            type=semver,pattern=v{{version}}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/images/price-feeder.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
