name: Release price-feeder

on:
  push:
    tags:
      - "price-feeder/v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      # Parse 'v*.*.*' semantic version from 'price-feeder/v*.*.*' and save to
      # the $GITHUB_ENV environment variable.
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/price-feeder/}" >> $GITHUB_ENV
      # Remove the possible pre-existing same tag for umee related tags instead
      # of price-feeder tags, since goreleaser enforces semantic versioning and
      # will error on non compliant tags.
      #
      # Ref: https://goreleaser.com/limitations/semver
      - name: Tag without prefix locally to avoid error in goreleaser
        run: |-
          git tag -d ${{ env.RELEASE_VERSION }} || echo "No such a tag exists before"
          git tag ${{ env.RELEASE_VERSION }} HEAD
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-validate --release-notes ./RELEASE_NOTES.md
          workdir: price-feeder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: price-feeder/${{ env.RELEASE_VERSION }}
