name: Images
on:
  pull_request:
    types: [ labeled, opened, synchronize ]
  push:
    branches:
      - main
      - 'release/**'

jobs:
  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref,'refs/heads/release/') || contains(github.event.pull_request.labels.*.name, 'Enable:ImagePublish')

    name: Publish Docker, GCP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pack-and-distribute 
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
