name: Images
on:
  pull_request:
    types: [ labeled ]
  push:
    branches:
      - '**'
jobs:
  publish:
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'enable.publishimage')
    name: Publish Docker, GCP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pack-and-distribute 
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
